modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "copyworld"
version = "${version}"
displayName = "CopyWorld"
authors = "Iru21"
description = '''
Adds a button to the edit world screen to quickly make a copy of your world!
'''
#logoFile = ""

[[dependencies.copyworld]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.copyworld]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.copyworld]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "copyworld.mixins.json"
